### ISSUE TITLE
Перенести функционал в админку

### ISSUE THREAD

**Issue by akuryachenko** [vkuryachenko/mysite#4]
https://github.com/vkuryachenko/mysite/blob/master/polls/models.py#L19-L21
Это вроде в QuestionAdmin должно быть? Никогда не видел, чтоб так декларировали в модели самой функцию для админки.

**Comment by vkuryachenko** [comment]
Настройка страницы списка объектов¶
http://djbook.ru/rel1.8/intro/tutorial02.html#customize-the-admin-change-list

http://djbook.ru/rel1.8/intro/tutorial02.html

Customize the admin change list

https://docs.djangoproject.com/en/1.9/intro/tutorial07/

10 марта 2016 г., 1:07 пользователь Andrew K notifications@github.com
написал:

**Comment by vkuryachenko** [comment]
В документации на list_display так и пишут
https://docs.djangoproject.com/es/1.9/ref/contrib/admin/#django.contrib.admin.ModelAdmin.list_display

Usually, elements of list_display that aren’t actual database fields can’t be used in sorting (because Django does all the sorting at the database level).

However, if an element of list_display represents a certain database field, you can indicate this fact by setting the admin_order_field attribute of the item.

For example:

from django.db import models
from django.contrib import admin
from django.utils.html import format_html

class Person(models.Model):
    first_name = models.CharField(max_length=50)
    color_code = models.CharField(max_length=6)

```
def colored_first_name(self):
    return format_html('<span style="color: #{};">{}</span>',
                       self.color_code,
                       self.first_name)

colored_first_name.admin_order_field = 'first_name'
```

class PersonAdmin(admin.ModelAdmin):
    list_display = ('first_name', 'colored_first_name')

**Comment by akuryachenko** [comment]
A string representing an **attribute on the ModelAdmin**. This behaves **same as the callable**. For example:
https://docs.djangoproject.com/es/1.9/ref/contrib/admin/#django.contrib.admin.ModelAdmin.list_display

**Comment by vkuryachenko** [comment]
polls/admin.py

def was_published_recently(self, obj):
        now = timezone.now()
        return now - datetime.timedelta(days=7) <= obj.pub_date <= now

```
was_published_recently.admin_order_field = 'pub_date'
was_published_recently.boolean = True
was_published_recently.short_description = 'Published last week?'
```
